### ISSUE TITLE
Error running op openELEC with Kodi 18

### ISSUE THREAD

**Issue by PanderMusubi** [intergalacticfm/plugin.video.intergalacticfm#6]
Error running op OpenELEC/LibreELEC/Raspbian with Kodi 18, see log file for errors.

[openELEC_ifm_addon_kodi_log.txt](https://github.com/intergalacticfm/plugin.video.intergalacticfm/files/3026519/openELEC_ifm_addon_kodi_log.txt)

**Comment by dromer** [comment]
This log seems to be related to ```plugin.audio.intergalacticfm``` ?

Also, Kodi18 still uses python 2.7? o.O

**Comment by dromer** [comment]
Works fine. Closing issue.
