### ISSUE TITLE
Murder Capital TV not appearing on channel list

### ISSUE THREAD

**Issue by elkrojo** [intergalacticfm/plugin.video.intergalacticfm#8]
Looks like the id label has been changed to "mtv" at source. However, the py script is looking for a match with "prc" from the resource file. At least that is what it looks like to me.

**Comment by PanderMusubi** [comment]
We are working on a new release that fixes that. Thanks for bringing it under our attention. Stay tuned for a new release.

**Comment by dromer** [comment]
Should be fixed in latest master/develop (available via kodi addons soon).
